const QUESTIONS = {
  math: [
    // ===== Easy MCQ =====
    {
      question: "If x² − 9 = 0, what is the value of x?",
      options: ["3 only", "−3 only", "3 or −3", "0"],
      correct: 2,
      difficulty: "easy",
      type: "mcq",
      explanation: "x² − 9 = 0 ⇒ x² = 9. Taking square root gives x = ±3.",
    },
    {
      question: "What is the value of (2³ × 2⁴)?",
      options: ["2⁷", "2¹²", "2⁸", "2¹"],
      correct: 0,
      difficulty: "easy",
      type: "mcq",
      explanation: "Using the law of indices: aᵐ × aⁿ = aᵐ⁺ⁿ, so 2³ × 2⁴ = 2⁷.",
    },
    {
      question: "If a = 3, find the value of a² − 2a.",
      options: ["3", "6", "9", "12"],
      correct: 0,
      difficulty: "easy",
      type: "mcq",
      explanation: "a² − 2a = 3² − 2×3 = 9 − 6 = 3.",
    },
    {
      question: "Which of the following is NOT a rational number?",
      options: ["0.25", "√2", "−3/7", "0.75"],
      correct: 1,
      difficulty: "easy",
      type: "mcq",
      explanation:
        "√2 cannot be expressed as a ratio of integers, so it is irrational.",
    },
    {
      question: "What is the solution of the equation 2x + 5 = 13?",
      options: ["3", "4", "5", "6"],
      correct: 1,
      difficulty: "easy",
      type: "mcq",
      explanation: "2x + 5 = 13 ⇒ 2x = 8 ⇒ x = 4.",
    },
    {
      question:
        "If the perimeter of a square is 20 cm, what is the length of one side?",
      options: ["4 cm", "5 cm", "6 cm", "8 cm"],
      correct: 1,
      difficulty: "easy",
      type: "mcq",
      explanation: "Perimeter of square = 4 × side. So side = 20 ÷ 4 = 5 cm.",
    },
    {
      question: "What is the value of 9⁰?",
      options: ["0", "1", "9", "Undefined"],
      correct: 1,
      difficulty: "easy",
      type: "mcq",
      explanation: "Any non-zero number raised to the power 0 is equal to 1.",
    },
    {
      question: "If x : y = 2 : 3 and x = 8, what is the value of y?",
      options: ["10", "12", "14", "16"],
      correct: 1,
      difficulty: "easy",
      type: "mcq",
      explanation: "x : y = 2 : 3 ⇒ x = 2k = 8 ⇒ k = 4. So y = 3k = 12.",
    },
    {
      question: "Which angle is formed between the hands of a clock at 3:00?",
      options: ["0°", "90°", "120°", "180°"],
      correct: 1,
      difficulty: "easy",
      type: "mcq",
      explanation:
        "At 3:00, the minute hand is at 12 and the hour hand is at 3, forming a right angle of 90°.",
    },
    {
      question:
        "If the area of a rectangle is 48 cm² and its length is 6 cm, find its breadth.",
      options: ["6 cm", "8 cm", "10 cm", "12 cm"],
      correct: 1,
      difficulty: "easy",
      type: "mcq",
      explanation:
        "Area = length × breadth ⇒ 48 = 6 × breadth ⇒ breadth = 8 cm.",
    },

    // ===== Easy TRUE/FALSE =====

    {
      question: "The square of any real number is always non-negative.",
      options: ["True", "False"],
      correct: 0,
      difficulty: "easy",
      type: "truefalse",
      explanation:
        "The square of a number is obtained by multiplying it by itself. A negative number squared also becomes positive.",
    },
    {
      question: "√49 is equal to ±7.",
      options: ["True", "False"],
      correct: 0,
      difficulty: "easy",
      type: "truefalse",
      explanation:
        "Since 7² = 49 and (−7)² = 49, the square root equation x² = 49 has two solutions: ±7.",
    },
    {
      question: "A linear equation in one variable has exactly one solution.",
      options: ["True", "False"],
      correct: 0,
      difficulty: "easy",
      type: "truefalse",
      explanation:
        "A linear equation like ax + b = c (where a ≠ 0) always has one and only one solution.",
    },
    {
      question: "Zero is neither positive nor negative.",
      options: ["True", "False"],
      correct: 0,
      difficulty: "easy",
      type: "truefalse",
      explanation:
        "Zero lies between positive and negative numbers and does not belong to either group.",
    },
    {
      question: "The value of a⁰ is 0 for any real number a.",
      options: ["True", "False"],
      correct: 1,
      difficulty: "easy",
      type: "truefalse",
      explanation: "For any non-zero real number a, a⁰ = 1, not 0.",
    },
    {
      question: "The sum of the angles of a triangle is 180°.",
      options: ["True", "False"],
      correct: 0,
      difficulty: "easy",
      type: "truefalse",
      explanation:
        "In Euclidean geometry, the sum of all interior angles of a triangle is always 180°.",
    },
    {
      question: "All prime numbers are odd.",
      options: ["True", "False"],
      correct: 1,
      difficulty: "easy",
      type: "truefalse",
      explanation:
        "The number 2 is a prime number and it is even, so not all prime numbers are odd.",
    },
    {
      question: "The product of two negative numbers is positive.",
      options: ["True", "False"],
      correct: 0,
      difficulty: "easy",
      type: "truefalse",
      explanation:
        "According to the rules of integers, multiplying two negative numbers gives a positive result.",
    },
    {
      question: "The value of π is exactly equal to 22/7.",
      options: ["True", "False"],
      correct: 1,
      difficulty: "easy",
      type: "truefalse",
      explanation:
        "π is an irrational number. 22/7 is only an approximate value of π.",
    },
    {
      question: "A square is a special type of rectangle.",
      options: ["True", "False"],
      correct: 0,
      difficulty: "easy",
      type: "truefalse",
      explanation:
        "A square satisfies all properties of a rectangle but has the additional condition that all sides are equal.",
    },

    // ===== Easy Fill in the Blanks =====
    {
      question: "The value of 6 + 4 is ____.",
      options: ["8", "9", "10", "12"],
      correct: 2,
      difficulty: "easy",
      type: "fillblanks",
      explanation: "6 + 4 = 10.",
    },
    {
      question: "The square root of 25 is ____.",
      options: ["4", "5", "6", "7"],
      correct: 1,
      difficulty: "easy",
      type: "fillblanks",
      explanation: "5 × 5 = 25.",
    },
    {
      question: "A rectangle has ____ sides.",
      options: ["3", "4", "5", "6"],
      correct: 1,
      difficulty: "easy",
      type: "fillblanks",
      explanation: "A rectangle has four sides.",
    },
    {
      question: "Half of 50 is ____.",
      options: ["20", "25", "30", "35"],
      correct: 1,
      difficulty: "easy",
      type: "fillblanks",
      explanation: "50 ÷ 2 = 25.",
    },
    {
      question: "The next number after 99 is ____.",
      options: ["100", "101", "98", "110"],
      correct: 0,
      difficulty: "easy",
      type: "fillblanks",
      explanation: "99 + 1 = 100.",
    },

    // ===== Easy Rapid Fire =====
    {
      question: "What is 8 + 2?",
      options: ["9", "10", "11", "12"],
      correct: 1,
      difficulty: "easy",
      type: "rapidfire",
      explanation: "8 + 2 = 10.",
    },
    {
      question: "What is 5²?",
      options: ["10", "15", "20", "25"],
      correct: 3,
      difficulty: "easy",
      type: "rapidfire",
      explanation: "5 × 5 = 25.",
    },
    {
      question: "How many sides does a square have?",
      options: ["3", "4", "5", "6"],
      correct: 1,
      difficulty: "easy",
      type: "rapidfire",
      explanation: "A square has four equal sides.",
    },
    {
      question: "What is 100 − 40?",
      options: ["50", "60", "70", "80"],
      correct: 1,
      difficulty: "easy",
      type: "rapidfire",
      explanation: "100 minus 40 equals 60.",
    },
    {
      question: "What is 3 × 4?",
      options: ["7", "10", "12", "15"],
      correct: 2,
      difficulty: "easy",
      type: "rapidfire",
      explanation: "3 multiplied by 4 equals 12.",
    },

    // ==== Medium MCQ ====
    {
      question: "What is the value of √169?",
      options: ["11", "12", "13", "14"],
      correct: 2,
      difficulty: "medium",
      type: "mcq",
      explanation: "13 × 13 = 169, so √169 = 13.",
    },
    {
      question: "Solve: 4x + 3 = 19",
      options: ["3", "4", "5", "6"],
      correct: 1,
      difficulty: "medium",
      type: "mcq",
      explanation: "4x = 16 ⇒ x = 4.",
    },
    {
      question: "What is 25% of 80?",
      options: ["15", "20", "25", "30"],
      correct: 1,
      difficulty: "medium",
      type: "mcq",
      explanation: "25% of 80 = 0.25 × 80 = 20.",
    },
    {
      question: "If the radius of a circle is 7 cm, what is its diameter?",
      options: ["7 cm", "10 cm", "12 cm", "14 cm"],
      correct: 3,
      difficulty: "medium",
      type: "mcq",
      explanation: "Diameter = 2 × radius = 2 × 7 = 14 cm.",
    },
    {
      question: "What is the LCM of 6 and 8?",
      options: ["12", "24", "36", "48"],
      correct: 1,
      difficulty: "medium",
      type: "mcq",
      explanation: "The lowest common multiple of 6 and 8 is 24.",
    },

    // ==== Medium True/False ====
    {
      question: "The square root of 81 is ±9.",
      options: ["True", "False"],
      correct: 0,
      difficulty: "medium",
      type: "truefalse",
      explanation: "Since 9² = 81 and (−9)² = 81, the solutions are ±9.",
    },
    {
      question: "An obtuse angle is greater than 90°.",
      options: ["True", "False"],
      correct: 0,
      difficulty: "medium",
      type: "truefalse",
      explanation: "An obtuse angle measures more than 90° but less than 180°.",
    },
    {
      question: "The value of 2⁵ is 10.",
      options: ["True", "False"],
      correct: 1,
      difficulty: "medium",
      type: "truefalse",
      explanation: "2⁵ = 32, not 10.",
    },
    {
      question: "A parallelogram has opposite sides equal.",
      options: ["True", "False"],
      correct: 0,
      difficulty: "medium",
      type: "truefalse",
      explanation: "In a parallelogram, opposite sides are equal and parallel.",
    },
    {
      question: "The sum of the angles of a quadrilateral is 360°.",
      options: ["True", "False"],
      correct: 0,
      difficulty: "medium",
      type: "truefalse",
      explanation: "All quadrilaterals have interior angles summing to 360°.",
    },

    // ==== Medium FillBlanks ====
    {
      question: "The cube of 3 is ____.",
      options: ["6", "9", "27", "81"],
      correct: 2,
      difficulty: "medium",
      type: "fillblanks",
      explanation: "3 × 3 × 3 = 27.",
    },
    {
      question: "The value of 7² − 10 is ____.",
      options: ["29", "39", "49", "59"],
      correct: 1,
      difficulty: "medium",
      type: "fillblanks",
      explanation: "49 − 10 = 39.",
    },
    {
      question:
        "The perimeter of a rectangle with length 10 cm and width 5 cm is ____.",
      options: ["20 cm", "25 cm", "30 cm", "35 cm"],
      correct: 2,
      difficulty: "medium",
      type: "fillblanks",
      explanation: "Perimeter = 2(l + w) = 2(10 + 5) = 30 cm.",
    },
    {
      question: "The value of 100 ÷ 0.5 is ____.",
      options: ["50", "100", "150", "200"],
      correct: 3,
      difficulty: "medium",
      type: "fillblanks",
      explanation:
        "Dividing by 0.5 is same as multiplying by 2, so 100 × 2 = 200.",
    },
    {
      question: "The next prime number after 11 is ____.",
      options: ["12", "13", "15", "17"],
      correct: 1,
      difficulty: "medium",
      type: "fillblanks",
      explanation: "13 is the next prime after 11.",
    },

    // ==== Medium Rapid Fire ====
    {
      question: "What is 12 × 12?",
      options: ["124", "144", "132", "156"],
      correct: 1,
      difficulty: "medium",
      type: "rapidfire",
      explanation: "12 × 12 = 144.",
    },
    {
      question: "What is 50% of 90?",
      options: ["40", "45", "50", "55"],
      correct: 1,
      difficulty: "medium",
      type: "rapidfire",
      explanation: "Half of 90 is 45.",
    },
    {
      question: "What is √225?",
      options: ["13", "14", "15", "16"],
      correct: 2,
      difficulty: "medium",
      type: "rapidfire",
      explanation: "15 × 15 = 225.",
    },
    {
      question: "What is 2³ × 2²?",
      options: ["16", "32", "64", "8"],
      correct: 1,
      difficulty: "medium",
      type: "rapidfire",
      explanation: "2³ × 2² = 2⁵ = 32.",
    },
    {
      question: "How many degrees are in a straight line?",
      options: ["90°", "180°", "270°", "360°"],
      correct: 1,
      difficulty: "medium",
      type: "rapidfire",
      explanation: "A straight line forms 180°.",
    },

    // ==== Hard MCQ ====
    {
      question: "If 2x² − 8 = 0, what is the value of x?",
      options: ["±2", "±4", "2 only", "4 only"],
      correct: 0,
      difficulty: "hard",
      type: "mcq",
      explanation: "2x² = 8 ⇒ x² = 4 ⇒ x = ±2.",
    },
    {
      question: "What is the value of log₁₀(1000)?",
      options: ["2", "3", "4", "10"],
      correct: 1,
      difficulty: "hard",
      type: "mcq",
      explanation: "10³ = 1000, so log₁₀(1000) = 3.",
    },
    {
      question: "If sin 30° = ?",
      options: ["1", "1/2", "√3/2", "0"],
      correct: 1,
      difficulty: "hard",
      type: "mcq",
      explanation: "The value of sin 30° is 1/2.",
    },
    {
      question: "What is the derivative of x²?",
      options: ["x", "2x", "x²", "2"],
      correct: 1,
      difficulty: "hard",
      type: "mcq",
      explanation: "The derivative of x² with respect to x is 2x.",
    },
    {
      question: "If the determinant of a 2×2 matrix is zero, the matrix is:",
      options: ["Invertible", "Singular", "Identity", "Orthogonal"],
      correct: 1,
      difficulty: "hard",
      type: "mcq",
      explanation:
        "A matrix with determinant 0 is called singular and is not invertible.",
    },

    // ==== Hard True/False ====
    {
      question: "The graph of y = x² is a parabola.",
      options: ["True", "False"],
      correct: 0,
      difficulty: "hard",
      type: "truefalse",
      explanation: "The equation y = x² forms a parabolic curve.",
    },
    {
      question: "Every continuous function is differentiable.",
      options: ["True", "False"],
      correct: 1,
      difficulty: "hard",
      type: "truefalse",
      explanation:
        "Some continuous functions (like |x| at x=0) are not differentiable.",
    },
    {
      question: "The sum of an infinite geometric series can be finite.",
      options: ["True", "False"],
      correct: 0,
      difficulty: "hard",
      type: "truefalse",
      explanation:
        "If |r| < 1, the infinite geometric series has a finite sum.",
    },
    {
      question: "π is a rational number.",
      options: ["True", "False"],
      correct: 1,
      difficulty: "hard",
      type: "truefalse",
      explanation:
        "π is irrational and cannot be expressed as a fraction of integers.",
    },
    {
      question: "The inverse of multiplication is division.",
      options: ["True", "False"],
      correct: 0,
      difficulty: "hard",
      type: "truefalse",
      explanation:
        "Division reverses multiplication, making it its inverse operation.",
    },

    // ==== Hard FillBlanks ====
    {
      question: "The value of 3³ + 4² is ____.",
      options: ["43", "41", "45", "47"],
      correct: 0,
      difficulty: "hard",
      type: "fillblanks",
      explanation: "3³ = 27 and 4² = 16, so total = 43.",
    },
    {
      question: "The roots of x² − 5x + 6 are ____.",
      options: ["2 and 3", "1 and 6", "−2 and −3", "3 and 5"],
      correct: 0,
      difficulty: "hard",
      type: "fillblanks",
      explanation: "(x − 2)(x − 3) = 0, so roots are 2 and 3.",
    },
    {
      question: "The value of tan 45° is ____.",
      options: ["0", "1", "√3", "1/2"],
      correct: 1,
      difficulty: "hard",
      type: "fillblanks",
      explanation: "tan 45° = 1.",
    },
    {
      question: "The area of a circle with radius 7 cm (π = 22/7) is ____.",
      options: ["144 cm²", "154 cm²", "164 cm²", "174 cm²"],
      correct: 1,
      difficulty: "hard",
      type: "fillblanks",
      explanation: "Area = πr² = (22/7) × 49 = 154 cm².",
    },
    {
      question: "The sum of the first 10 natural numbers is ____.",
      options: ["45", "50", "55", "60"],
      correct: 2,
      difficulty: "hard",
      type: "fillblanks",
      explanation: "Sum formula n(n+1)/2 ⇒ 10×11/2 = 55.",
    },

    // ==== Hard Rapid Fire ====
    {
      question: "What is 13²?",
      options: ["156", "169", "176", "196"],
      correct: 1,
      difficulty: "hard",
      type: "rapidfire",
      explanation: "13 × 13 = 169.",
    },
    {
      question: "What is √400?",
      options: ["10", "15", "20", "25"],
      correct: 2,
      difficulty: "hard",
      type: "rapidfire",
      explanation: "20 × 20 = 400.",
    },
    {
      question: "What is 2⁶?",
      options: ["32", "48", "64", "128"],
      correct: 2,
      difficulty: "hard",
      type: "rapidfire",
      explanation: "2⁶ = 64.",
    },
    {
      question: "What is the cube root of 27?",
      options: ["2", "3", "4", "5"],
      correct: 1,
      difficulty: "hard",
      type: "rapidfire",
      explanation: "3 × 3 × 3 = 27.",
    },
    {
      question: "How many degrees are in a full circle?",
      options: ["90°", "180°", "270°", "360°"],
      correct: 3,
      difficulty: "hard",
      type: "rapidfire",
      explanation: "A full rotation equals 360°.",
    },
  ],
};
